### ISSUE TITLE
Background_opacity no funciona

### ISSUE THREAD

**Issue by Mestag** [antoniosarosi/dotfiles#13]
no se porque pero cuado pongo la opacidad mas baja la terminal se pone mas negra no importa si es por pycritty o por alacritty.yml

**Comment by antoniosarosi** [comment]
Porque no tienes ningún compositor, instala Picom y ponlo en marcha en segundo plano.

**Comment by Mestag** [comment]
ya lo tengo instalado y en segundo plano solo puedo ponerle transparencia con
`opacity-rule = [
  "85:class_g = 'Alacritty'",
];`

**Comment by Mestag** [comment]
Algo raro es que la opacidad si funciona en rofi pero no en alacritty

**Comment by AlphaTechnolog** [comment]
Trata usando en vez de `picom` utiliza `compton`, es otra alternativa!, puedes en tu `~/.config/qtile/autostart.sh`, agregar el siguiente comando:

```
compton -r 12 -o 0.00 -l 15 -t 15 -I 0.028 -O 0.03 -D 3 -c -f -C -F -G -b &
```

**Comment by AlphaTechnolog** [comment]
esto lo que hace es (aparte de dejarte usar transparencias) pone abajo de las ventanas una *moderada* sombra!
*NOTA*: de hecho es peque#a

**Comment by Mestag** [comment]
hace que funcione rofi como antes pero sigue sin haber transparencia en alacritty

**Comment by AlphaTechnolog** [comment]
Que version de alacritty estas usando?
Yo uso la alacritty 0.4.3 en debian 9, y me funciona con compton, pues no logre instalar picom

**Comment by AlphaTechnolog** [comment]
Pienso que el problema es con alacritty, pues `rofi` funciona con `compton` y `picom` pero `alacritty` no!

**Comment by AlphaTechnolog** [comment]
Te dejo un ejemplo de como se ve en mi pc:
![2021-03-03-130354_2646x1024_scrot](https://user-images.githubusercontent.com/54639968/109842978-fe2b9980-7c20-11eb-95a9-17420b02ed5e.png)

**Comment by Mestag** [comment]
yo tengo `alacritty` 0.7.2 (5ac8060b)

**Comment by AlphaTechnolog** [comment]
Instalaste alacritty por los repos de tu distro o lo instalaste con el bash script que da la pagina o con un deb o rpm o algo similar?

**Comment by Mestag** [comment]
lo instale con las repos de arch osea pacman

**Comment by CyberGsus** [comment]
estaría bien que pusieras como tienes el alacritty.yml, puede que el problema resida en algún error cargando otra parte de la configuración.

**Comment by Mestag** [comment]
![2021-03-13-143201_1024x600_scrot](https://user-images.githubusercontent.com/79472510/111038645-ee723900-8408-11eb-9642-1d1fc031d6ca.png)

**Comment by AlphaTechnolog** [comment]
Intenta poniendo en background opacity 0.95

**Comment by AlphaTechnolog** [comment]
Seguramente la opacidad al ser literalmente nula no se ve por lo tanto aumentando a 0.95 se debería ver bien ( en mi opinión )

**Comment by AlphaTechnolog** [comment]
> Seguramente la opacidad al ser literalmente nula no se ve por lo tanto aumentando a 0.95 se debería ver bien ( en mi opinión ) con pycritty el comando es `pycritty -o 0.95`

**Comment by edwz-dev** [comment]
Ehh, tuve varios problemas con el picom, a la final modifiqué mi archivo alacritty.yml, le cambié algunos valores y funcionó, creo que solo le cambié el background_opacity = 1 a 0.5 y funcionó, no sé en tu caso por qué no funciona

**Comment by edwz-dev** [comment]
¿Ya tienes configurados los monitores? ayuda :,v

**Comment by Mestag** [comment]
nop no funciono F

**Comment by AlphaTechnolog** [comment]
asi me funciono a mi:

```yaml
background_opacity: 0.95
colors:
  bright:
    black: '0x5c6370'
    blue: '0x61afef'
    cyan: '0x56b6c2'
    green: '0x98c379'
    magenta: '0xc678dd'
    red: '0xe06c75'
    white: '0xe6efff'
    yellow: '0xd19a66'
  dim:
    black: '0x1e2127'
    blue: '0x61afef'
    cyan: '0x56b6c2'
    green: '0x98c379'
    magenta: '0xc678dd'
    red: '0xe06c75'
    white: '0x828791'
    yellow: '0xd19a66'
  normal:
    black: '0x1e2127'
    blue: '0x61afef'
    cyan: '0x56b6c2'
    green: '0x98c379'
    magenta: '0xc678dd'
    red: '0xe06c75'
    white: '0x828791'
    yellow: '0xd19a66'
  primary:
    background: '0x1e2127'
    bright_foreground: '0xe6efff'
    foreground: '0xabb2bf'
font:
  bold:
    family: agave Nerd Font
  italic:
    family: agave Nerd Font
  normal:
    family: agave Nerd Font
    style: Regular
  size: 14.0
window:
  padding:
    x: 0
    y: 0
```
